# Generated by Django 3.2.3 on 2021-05-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs - Married Female'), ('Mis', 'Miss - Unmarried status'), ('Ms', 'Ms- Female Unknown Marital status'), ('Mx', 'Mx - Gender neutral, do not wish to specify their gender or identify as non-binary'), ('Dr', 'Doctor - Medical or has Terminal Education PhD etc...'), ('ESQ', 'Esquire - gender-neutral way to address a lawyer'), ('RAB', 'Ordained teacher of Judaism'), ('REV', 'Christian Clergy-person'), ('VEN', 'Venerable- ordained teacher of buddhism'), ('IMA', 'Islamic clergyperson'), ('ELD', 'A ruling member of certain religious followings'), ('Fr', 'Catholic '), ('Pr', 'Pastor - an ordained member of certain religious followings'), ('Sr', 'Sister - a nun or other catholic religious female'), ('Br', 'Brother - a non priest member of certian religious followings')], default='Mx', max_length=3),
        ),
    ]
