# pyproject.toml
[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
collect_ignore_glob = 
[
  "*_ignore.py"
]
python_classes =[
  "*Suite",
  "Suite*",
  "Test*",
  "*Test",
]
python_files = ['test_*.py', 'check_*.py', "example_*.py",
"*_test.py",
"*_check.py",
"*_example.py",

]
testpaths = [
  "tests",
]

[tool.coverage]

[tool.coverage.run]
branch = true

[tool.coverage.report]
[tool.coverage.report.excludeLines]
  pragma= 'no cover' # Have to re-enable the standard pragma

  ignore_errors = true

[tool.coverage.html]
directory = ['coverage_html_report']