# Generated by Django 3.1.7 on 2021-04-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=3, null=True)),
                ('location_state', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
