# Generated by Django 3.1.3 on 2020-11-06 20:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import patients.models.patient
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionSite",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.CharField(max_length=100)),
                ("site_street1", models.CharField(max_length=100)),
                ("site_street2", models.CharField(max_length=100)),
                ("site_state", models.CharField(max_length=100)),
                ("site_city", models.CharField(max_length=100)),
                ("site_zipcode", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="RequestingSite",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.CharField(max_length=100)),
                ("site_street1", models.CharField(max_length=100)),
                ("site_street2", models.CharField(max_length=100)),
                ("site_state", models.CharField(max_length=100)),
                ("site_city", models.CharField(max_length=100)),
                ("site_zipcode", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "honorific_prefix",
                    models.CharField(
                        blank=True,
                        help_text="The portion of the name identified by the following abbreviations no punctuation: Dr / Mrs / Mr",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "honorific_suffix",
                    models.CharField(
                        blank=True,
                        help_text="The identifying portion of a person's name.\nExamples (Letters Only, capitialization insignificant): Jr, Sr, I, II, III, PhD, MD, RN.",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                (
                    "birth_month",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                1,
                                message="Zero or negative numbers are not allowed in this field.",
                            ),
                            django.core.validators.MaxValueValidator(
                                12, message="There is no 13th Month."
                            ),
                        ]
                    ),
                ),
                (
                    "birth_day",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, message="No month has less thand 1 day."
                            ),
                            django.core.validators.MaxValueValidator(
                                31, message="No month has more than 31 days."
                            ),
                        ]
                    ),
                ),
                (
                    "birth_year",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                1900,
                                message="Unlikely Patient was born before the 20th Century (before 1900)",
                            ),
                            django.core.validators.MaxValueValidator(
                                patients.models.patient.max_year_validator,
                                message="Cannot be born after this year.",
                            ),
                        ]
                    ),
                ),
                (
                    "ethinicty",
                    models.CharField(
                        choices=[
                            (None, "No Selection, Declined To Answer"),
                            (
                                "ASN",
                                "Asian - Far East, Southeast Asia, or the Indian subcontinent including, for example, Cambodia, China, India, Japan, Korea, Malaysia, Pakistan, the Philippine Islands, Thailand, and Vietnam.",
                            ),
                            (
                                "BLK",
                                "Black - origins in any of the Black racial groups of Africa including Carribean Islands.",
                            ),
                            ("NAT", "Native American or Alaskan Native."),
                            (
                                "HPN",
                                "Hispanic - Centeral and South America, Carribbean Islands.",
                            ),
                            (
                                "MDE",
                                "Middle Eastern - the Middle East, or North Africa.",
                            ),
                            (
                                "HWN",
                                "Native Hawaii, Guam, Samoa, or other Pacific Islands.",
                            ),
                            ("OTH", "Other/Multiple"),
                            ("WHT", "White-origins in Europe."),
                        ],
                        default="No Selection, Declined To Answer",
                        max_length=3,
                    ),
                ),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("staff_notes", models.TextField()),
                (
                    "edited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_edited",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LabResult",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="media/test_results.jpg",
                        upload_to="covid19/test_results/",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            (None, "(Unknown)"),
                            ("POS", "Positive"),
                            ("NEG", "Negative"),
                            ("INC", "Inconclusive"),
                            ("CNT", "Cancelled"),
                        ],
                        default="(Unknown)",
                        max_length=3,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUB", "Submitted"),
                            ("UDT", "Results Updating"),
                            ("PEN", "Pending Lab Results"),
                            ("REC", "Sample Received"),
                            ("OTH", "Sample Not Yet Received"),
                        ],
                        default="OTH",
                        max_length=3,
                    ),
                ),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("staff_notes", models.TextField()),
                (
                    "edited_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_edited",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Consent",
            fields=[
                (
                    "slug",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="media/consent_form.jpg", upload_to="covid19/consent/"
                    ),
                ),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("staff_notes", models.TextField()),
                (
                    "edited_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consent_edited",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuthorizedParties",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("party_name", models.CharField(max_length=100, null=True)),
                (
                    "written_authorization",
                    models.ImageField(
                        blank=True,
                        default="media/consent_form.jpg",
                        null=True,
                        upload_to="",
                    ),
                ),
                (
                    "verbal_authorization",
                    models.FileField(blank=True, default=None, null=True, upload_to=""),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("staff_notes", models.TextField()),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.patient",
                    ),
                ),
            ],
        ),
    ]
