# Generated by Django 3.1.3 on 2020-11-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "M",
                        "I identify as a male or a man (i.e. male, cis-gender male), and prefer to be called sir",
                    ),
                    (
                        "F",
                        "I identify as a female or a woman (i.e. female, cis-gender female),  and prefer to be called ma'am.",
                    ),
                    (
                        "MTF",
                        "Assigned male at birth, but currently identify as female.",
                    ),
                    ("FTM", "Assigned female at birth but currently identify as male."),
                    ("NBN", "Neither male nor female, somewhere in between."),
                ],
                max_length=3,
                null=True,
            ),
        ),
    ]
